sudo: required
dist: trusty
language: cpp
cache: apt
os:
- linux
compiler:
- gcc
before_script:
- sudo apt-get update
- sudo apt-get install -y git build-essential
- sudo apt-get install -y clang-3.8 clang++-3.8 llvm-3.8-dev libc++1 libc++-dev
- sudo apt-get install -y libgflags-dev
script:
- make clean all
- make clean all GRANARY_TARGET=release
