sudo: required
dist: trusty
language: cpp
cache: apt
os:
- linux
compiler:
- gcc
before_script:
- sudo apt-get update
- sudo apt-get install -y git build-essential
- sudo apt-get install -y clang-3.8 clang++-3.8 llvm-3.8-dev libc++1 libc++-dev
- sudo apt-get install -y libgflags-dev
- mkdir build && cd build
script:
- cmake -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ .. && make clean all
- cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ .. && make clean all
