sudo: required
dist: trusty
language: cpp
cache: apt
os:
- linux
compiler:
- gcc
before_script:
- sudo apt-get update
- sudo apt-get install -y git build-essential
- sudo apt-get install -y clang llvm-dev libc++1 libc++-dev
script:
- ./scripts/build.sh
